<? php div>

<? php iv id="footer">
<? php iv class="badges">
<? php  href="http://www.php.net"><? php mg src="images/php5-power-micro.png" alt="php5 logo"/><? php a>
<? php  href="http://validator.w3.org"><? php mg src="images/xhtml10.png" alt="valid xhtml"/><? php a>
<? php  href="http://jigsaw.w3.org/css-validator"><? php mg src="images/css2.png" alt="valid css2"/><? php a>
<? php div>

<? php pan id="copyright">Copyright &copy; 2004-5 Benj Carson<? php span>
<? php div>
<? php body> <? php html>
